# Generated by Django 4.1.5 on 2024-04-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0004_remove_entities_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_by', models.SmallIntegerField(default=0)),
                ('updated_by', models.SmallIntegerField(default=0)),
                ('deleted_by', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('benifits', models.TextField()),
                ('pay_types', models.TextField()),
                ('experience', models.TextField()),
                ('descriptions', models.TextField()),
                ('qualifications', models.TextField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_by', models.SmallIntegerField(default=0)),
                ('updated_by', models.SmallIntegerField(default=0)),
                ('deleted_by', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(default='white', max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityHasCareer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('careers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.careers')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entities')),
                ('tags', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.careertags')),
            ],
        ),
        migrations.CreateModel(
            name='CareerHasQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('section', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_by', models.SmallIntegerField(default=0)),
                ('updated_by', models.SmallIntegerField(default=0)),
                ('deleted_by', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('careers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasquestions', to='hr.careers')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasquestions', to='hr.careerquestions')),
            ],
        ),
        migrations.CreateModel(
            name='CareerAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entities')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.careerquestions')),
            ],
        ),
    ]
