# Generated by Django 4.1.5 on 2024-06-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('hr', '0002_alter_entityhascareer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranswers',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.files'),
        ),
    ]
