# Generated by Django 4.1.5 on 2024-06-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_careeranswers_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerquestions',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
