# Generated by Django 4.1.5 on 2024-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_schedule_scheduledetails_timelogs_timesheets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='log_status',
            field=models.CharField(default='unused', max_length=50),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='log_type',
            field=models.CharField(default='work', max_length=50),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='work_area_code',
            field=models.CharField(default='WFH', max_length=50),
        ),
    ]
