# Generated by Django 4.1.5 on 2024-07-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_timelogs_log_status_alter_timelogs_log_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetails',
            name='multi_day',
            field=models.CharField(default='False', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledetails',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduleDetails', to='hr.schedule'),
        ),
    ]
