# Generated by Django 4.1.5 on 2024-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_careerplatforms_entityhascareer_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerquestions',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
