# Generated by Django 5.1.1 on 2024-10-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_careerquestions_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranswers',
            name='careers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.careers'),
        ),
    ]
