# Generated by Django 5.1.1 on 2024-11-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact_number', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('company_email', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='entity.entities')),
            ],
        ),
    ]
