# Generated by Django 4.1.5 on 2024-04-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_entities_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='birth_place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entities',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='civil_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entities',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entities',
            name='permanent_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='entities',
            name='present_address',
            field=models.TextField(default=''),
        ),
    ]
