# Generated by Django 5.1.1 on 2024-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_experiencedetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='children',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
