# Generated by Django 4.1.5 on 2024-04-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_entities_age_entities_birth_place_entities_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entities',
            name='address',
        ),
    ]
