# Generated by Django 5.1.1 on 2024-10-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_remove_entities_address'),
        ('hr', '0010_careeranswers_careers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_company', models.CharField(default='', max_length=50)),
                ('position_held', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('handled', models.CharField(default='', max_length=50)),
                ('stay_length', models.CharField(default='', max_length=50)),
                ('leave_reason', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entities',
            name='alternative_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='birth_order',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='children',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entities',
            name='education',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entities',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='EntityDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.CharField(default='', max_length=50)),
                ('us_time', models.CharField(default='', max_length=50)),
                ('work_in_office', models.CharField(default='', max_length=50)),
                ('transpo', models.CharField(default='', max_length=50)),
                ('application', models.CharField(default='', max_length=50)),
                ('start', models.CharField(default='', max_length=50)),
                ('condition', models.CharField(default='', max_length=50)),
                ('part_time', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entities')),
                ('platforms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.careerplatforms')),
            ],
        ),
        migrations.CreateModel(
            name='EntityHasExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entities')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasexperience', to='entity.experience')),
            ],
        ),
    ]
