# Generated by Django 5.1.1 on 2024-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_alter_entities_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedetails',
            name='order',
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
